### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by ano251** [madhuakula/kubernetes-goat#115]
Hi,

I am trying to deploy k8s-goat on my Mac Pro M2 but facing this issue:

1. system-monitor-deployment-* pod keep on crashing 
log:
exec /usr/local/bin/gotty: exec format error

2. hunger-check-deployment-* pod keep crashing

log:
exec /usr/local/bin/gotty: exec format error

Can you help?
Thanks,

**Comment by madhuakula** [comment]
The fix has been pushed by @SumoSumir will update the upstream images and close the issue after that

**Comment by SumoSumir** [comment]
Hi 
Sorry I had missed the hunger-check pod crash earlier. Have updated that Dockerfile as well.
Please update this image as well.

**Comment by galileotester** [comment]
Hi, I got this issue with M1 chip, tried to to build the gotty on my VM, modify the Dockerfile in infrastructure dir (hunger-check and system-monitor) to download the pre-built gotty, but when I run ./setup-kubernetes-goat.sh, it didn't work. I think I missed a step somewhere to get the setup shell calls the Dockerfile. Please help. Thanks

**Comment by madhuakula** [comment]
Fixed and pushed the changes to container image

**Comment by DanyAssuid** [comment]
@madhuakula I have the same error 
Can help me please ? 
I’m on Mac OS M2

**Comment by SumoSumir** [comment]
hey @madhuakula 
Am seeing that gotty is unreliable in arm machines, would you be willing to switch web terminals?

I've looked over the following options:
1. webtty - https://github.com/maxmcd/webtty?tab=readme-ov-file
+simple
-session management w/ the connection strings will be an unnecessary burden for our use case

2. witty - https://github.com/syssecfsu/witty?tab=readme-ov-file 
+I like the UI but am 
-unsure if something with these many features is needed 
-also last release was in 2022

3. cloudshell - https://github.com/zephinzer/cloudshell
+Simple visual UI
+premade dockerfiles 
-not many stars

4. tty-share - https://github.com/elisescu/tty-share
+Simple
+special mention of support for other architectures 
+pre-made dockerfiles
-provides for public terminal


Am currently leaning towards no. 4. 
Let me know if you concur - I'll test out the images on my pi5 and a few m1 & m2 machines and then raise a PR

**Comment by AnthonyH26** [comment]
So the issue here is not due to the fact of unmaintained web terminal (Although it has been picked up again - https://github.com/sorenisanerd/gotty), but its all due to which machine the docker container is built on then published, so although there is the if statement in the Dockerfiles, if the container is built on AMD64 architecture , it is built with AMD64 so therefore exec errors when running on ARM devices.

I temporarily uploaded new containers - https://hub.docker.com/u/anthonyh26 which need to be changed within the deployment.yaml within scenarios/hunger-check and scenarios/system-monitor folders

For ARM deployments I have forked with the necessary changes and pre-built images for anyone stumbling across this issue for a 1-click deploy - https://github.com/AnthonyH26/kubernetes-goat

**Comment by reegnz** [comment]
This is still an issue, just tried from a fresh clone.

Also can confirm that the fix of @AnthonyH26 works. Would be neat to incorporate those fixes.
